/*
** $Id: lua.c $
** Lua stand-alone interpreter
** See Copyright Notice in lua.h
*/

#define lua_c

#include "lprefix.h"


#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <signal.h>

#include "lua.h"

#include "lauxlib.h"
#include "lualib.h"


#if !defined(LUA_PROGNAME)
#define LUA_PROGNAME		"lua"
#endif

#if !defined(LUA_INIT_VAR)
#define LUA_INIT_VAR		"LUA_INIT"
#endif

#define LUA_INITVARVERSION	LUA_INIT_VAR LUA_VERSUFFIX


static lua_State *globalL = NULL;

static const char *progname = LUA_PROGNAME;


#if defined(LUA_USE_POSIX)   /* { */

/*
** Use 'sigaction' when available.
*/
static void setsignal (int sig, void (*handler)(int)) {
  struct sigaction sa;
  sa.sa_handler = handler;
  sa.sa_flags = 0;
  sigemptyset(&sa.sa_mask);  /* do not mask any signal */
  sigaction(sig, &sa, NULL);
}

#else           /* }{ */

#define setsignal            signal

#endif                               /* } */


/*
** Hook set by signal function to stop the interpreter.
*/
static void lstop (lua_State *L, lua_Debug *ar) {
  (void)ar;  /* unused arg. */
  lua_sethook(L, NULL, 0, 0);  /* reset hook */
  luaL_error(L, "interrupted!");
}


/*
** Function to be called at a C signal. Because a C signal cannot
** just change a Lua state (as there is no proper synchronization),
** this function only sets a hook that, when called, will stop the
** interpreter.
*/
static void laction (int i) {
  int flag = LUA_MASKCALL | LUA_MASKRET | LUA_MASKLINE | LUA_MASKCOUNT;
  setsignal(i, SIG_DFL); /* if another SIGINT happens, terminate process */
  lua_sethook(globalL, lstop, flag, 1);
}


static void print_usage (const char *badoption) {
  lua_writestringerror("%s: ", progname);
  if (badoption[1] == 'e' || badoption[1] == 'l')
    lua_writestringerror("'%s' needs argument\n", badoption);
  else
    lua_writestringerror("unrecognized option '%s'\n", badoption);
  lua_writestringerror(
  "usage: %s [options] [script [args]]\n"
  "Available options are:\n"
  "  -e stat   execute string 'stat'\n"
  "  -i        enter interactive mode after executing 'script'\n"
  "  -l mod    require library 'mod' into global 'mod'\n"
  "  -l g=mod  require library 'mod' into global 'g'\n"
  "  -v        show version information\n"
  "  -E        ignore environment variables\n"
  "  -W        turn warnings on\n"
  "  --        stop handling options\n"
  "  -         stop handling options and execute stdin\n"
  ,
  progname);
}


/*
** Prints an error message, adding the program name in front of it
** (if present)
*/
static void l_message (const char *pname, const char *msg) {
  if (pname) lua_writestringerror("%s: ", pname);
  lua_writestringerror("%s\n", msg);
}


/*
** Check whether 'status' is not OK and, if so, prints the error
** message on the top of the stack. It assumes that the error object
** is a string, as it was either generated by Lua or by 'msghandler'.
*/
static int report (lua_State *L, int status) {
  if (status != LUA_OK) {
    const char *msg = lua_tostring(L, -1);
    l_message(progname, msg);
    lua_pop(L, 1);  /* remove message */
  }
  return status;
}


/*
** Message handler used to run all chunks
*/
static int msghandler (lua_State *L) {
  const char *msg = lua_tostring(L, 1);
  if (msg == NULL) {  /* is error object not a string? */
    if (luaL_callmeta(L, 1, "__tostring") &&  /* does it have a metamethod */
        lua_type(L, -1) == LUA_TSTRING)  /* that produces a string? */
      return 1;  /* that is the message */
    else
      msg = lua_pushfstring(L, "(error object is a %s value)",
                               luaL_typename(L, 1));
  }
  luaL_traceback(L, L, msg, 1);  /* append a standard traceback */
  return 1;  /* return the traceback */
}


/*
** Interface to 'lua_pcall', which sets appropriate message function
** and C-signal handler. Used to run all chunks.
*/
static int docall (lua_State *L, int narg, int nres) {
  int status;
  int base = lua_gettop(L) - narg;  /* function index */
  lua_pushcfunction(L, msghandler);  /* push message handler */
  lua_insert(L, base);  /* put it under function and args */
  globalL = L;  /* to be available to 'laction' */
  setsignal(SIGINT, laction);  /* set C-signal handler */
  status = lua_pcall(L, narg, nres, base);
  setsignal(SIGINT, SIG_DFL); /* reset C-signal handler */
  lua_remove(L, base);  /* remove message handler from the stack */
  return status;
}


static void print_version (void) {
  lua_writestring(LUA_COPYRIGHT, strlen(LUA_COPYRIGHT));
  lua_writeline();
}


/*
** Create the 'arg' table, which stores all arguments from the
** command line ('argv'). It should be aligned so that, at index 0,
** it has 'argv[script]', which is the script name. The arguments
** to the script (everything after 'script') go to positive indices;
** other arguments (before the script name) go to negative indices.
** If there is no script name, assume interpreter's name as base.
** (If there is no interpreter's name either, 'script' is -1, so
** table sizes are zero.)
*/
static void createargtable (lua_State *L, char **argv, int argc, int script) {
  int i, narg;
  narg = argc - (script + 1);  /* number of positive indices */
  lua_createtable(L, narg, script + 1);
  for (i = 0; i < argc; i++) {
    lua_pushstring(L, argv[i]);
    lua_rawseti(L, -2, i - script);
  }
  lua_setglobal(L, "arg");
}


static int dochunk (lua_State *L, int status) {
  if (status == LUA_OK) status = docall(L, 0, 0);
  return report(L, status);
}


static int dofile (lua_State *L, const char *name) {
  return dochunk(L, luaL_loadfile(L, name));
}


static int dostring (lua_State *L, const char *s, const char *name) {
  return dochunk(L, luaL_loadbuffer(L, s, strlen(s), name));
}


/*
** Receives 'globname[=modname]' and runs 'globname = require(modname)'.
** If there is no explicit modname and globname contains a '-', cut
** the sufix after '-' (the "version") to make the global name.
*/
static int dolibrary (lua_State *L, char *globname) {
  int status;
  char *suffix = NULL;
  char *modname = strchr(globname, '=');
  if (modname == NULL) {  /* no explicit name? */
    modname = globname;  /* module name is equal to global name */
    suffix = strchr(modname, *LUA_IGMARK);  /* look for a suffix mark */
  }
  else {
    *modname = '\0';  /* global name ends here */
    modname++;  /* module name starts after the '=' */
  }
  lua_getglobal(L, "require");
  lua_pushstring(L, modname);
  status = docall(L, 1, 1);  /* call 'require(modname)' */
  if (status == LUA_OK) {
    if (suffix != NULL)  /* is there a suffix mark? */
      *suffix = '\0';  /* remove sufix from global name */
    lua_setglobal(L, globname);  /* globname = require(modname) */
  }
  return report(L, status);
}


/*
** Push on the stack the contents of table 'arg' from 1 to #arg
*/
static int pushargs (lua_State *L) {
  int i, n;
  if (lua_getglobal(L, "arg") != LUA_TTABLE)
    luaL_error(L, "'arg' is not a table");
  n = (int)luaL_len(L, -1);
  luaL_checkstack(L, n + 3, "too many arguments to script");
  for (i = 1; i <= n; i++)
    lua_rawgeti(L, -i, i);
  lua_remove(L, -i);  /* remove table from the stack */
  return n;
}


static int handle_script (lua_State *L, char **argv) {
  int status;
  const char *fname = argv[0];
  if (strcmp(fname, "-") == 0 && strcmp(argv[-1], "--") != 0)
    fname = NULL;  /* stdin */
  status = luaL_loadfile(L, fname);
  if (status == LUA_OK) {
    int n = pushargs(L);  /* push arguments to script */
    status = docall(L, n, LUA_MULTRET);
  }
  return report(L, status);
}


/* bits of various argument indicators in 'args' */
#define has_error	1	/* bad option */
#define has_i		2	/* -i */
#define has_v		4	/* -v */
#define has_e		8	/* -e */
#define has_E		16	/* -E */


/*
** Traverses all arguments from 'argv', returning a mask with those
** needed before running any Lua code or an error code if it finds any
** invalid argument. In case of error, 'first' is the index of the bad
** argument.  Otherwise, 'first' is -1 if there is no program name,
** 0 if there is no script name, or the index of the script name.
*/
static int collectargs (char **argv, int *first) {
  int args = 0;
  int i;
  if (argv[0] != NULL) {  /* is there a program name? */
    if (argv[0][0])  /* not empty? */
      progname = argv[0];  /* save it */
  }
  else {  /* no program name */
    *first = -1;
    return 0;
  }
  for (i = 1; argv[i] != NULL; i++) {  /* handle arguments */
    *first = i;
    if (argv[i][0] != '-')  /* not an option? */
        return args;  /* stop handling options */
    switch (argv[i][1]) {  /* else check option */
      case '-':  /* '--' */
        if (argv[i][2] != '\0')  /* extra characters after '--'? */
          return has_error;  /* invalid option */
        *first = i + 1;
        return args;
      case '\0':  /* '-' */
        return args;  /* script "name" is '-' */
      case 'E':
        if (argv[i][2] != '\0')  /* extra characters? */
          return has_error;  /* invalid option */
        args |= has_E;
        break;
      case 'W':
        if (argv[i][2] != '\0')  /* extra characters? */
          return has_error;  /* invalid option */
        break;
      case 'i':
        args |= has_i;  /* (-i implies -v) *//* FALLTHROUGH */
      case 'v':
        if (argv[i][2] != '\0')  /* extra characters? */
          return has_error;  /* invalid option */
        args |= has_v;
        break;
      case 'e':
        args |= has_e;  /* FALLTHROUGH */
      case 'l':  /* both options need an argument */
        if (argv[i][2] == '\0') {  /* no concatenated argument? */
          i++;  /* try next 'argv' */
          if (argv[i] == NULL || argv[i][0] == '-')
            return has_error;  /* no next argument or it is another option */
        }
        break;
      default:  /* invalid option */
        return has_error;
    }
  }
  *first = 0;  /* no script name */
  return args;
}


/*
** Processes options 'e' and 'l', which involve running Lua code, and
** 'W', which also affects the state.
** Returns 0 if some code raises an error.
*/
static int runargs (lua_State *L, char **argv, int n) {
  int i;
  for (i = 1; i < n; i++) {
    int option = argv[i][1];
    lua_assert(argv[i][0] == '-');  /* already checked */
    switch (option) {
      case 'e':  case 'l': {
        int status;
        char *extra = argv[i] + 2;  /* both options need an argument */
        if (*extra == '\0') extra = argv[++i];
        lua_assert(extra != NULL);
        status = (option == 'e')
                 ? dostring(L, extra, "=(command line)")
                 : dolibrary(L, extra);
        if (status != LUA_OK) return 0;
        break;
      }
      case 'W':
        lua_warning(L, "@on", 0);  /* warnings on */
        break;
    }
  }
  return 1;
}


static int handle_luainit (lua_State *L) {
  const char *name = "=" LUA_INITVARVERSION;
  const char *init = getenv(name + 1);
  if (init == NULL) {
    name = "=" LUA_INIT_VAR;
    init = getenv(name + 1);  /* try alternative name */
  }
  if (init == NULL) return LUA_OK;
  else if (init[0] == '@')
    return dofile(L, init+1);
  else
    return dostring(L, init, name);
}


/*
** {==================================================================
** Read-Eval-Print Loop (REPL)
** ===================================================================
*/

#if !defined(LUA_PROMPT)
#define LUA_PROMPT		"> "
#define LUA_PROMPT2		">> "
#endif

#if !defined(LUA_MAXINPUT)
#define LUA_MAXINPUT		512
#endif


/*
** lua_stdin_is_tty detects whether the standard input is a 'tty' (that
** is, whether we're running lua interactively).
*/
#if !defined(lua_stdin_is_tty)	/* { */

#if defined(LUA_USE_POSIX)	/* { */

#include <unistd.h>
#define lua_stdin_is_tty()	isatty(0)

#elif defined(LUA_USE_WINDOWS)	/* }{ */

#include <io.h>
#include <windows.h>

#define lua_stdin_is_tty()	_isatty(_fileno(stdin))

#else				/* }{ */

/* ISO C definition */
#define lua_stdin_is_tty()	1  /* assume stdin is a tty */

#endif				/* } */

#endif				/* } */


/*
** lua_readline defines how to show a prompt and then read a line from
** the standard input.
** lua_saveline defines how to "save" a read line in a "history".
** lua_freeline defines how to free a line read by lua_readline.
*/
#if !defined(lua_readline)	/* { */

#if defined(LUA_USE_READLINE)	/* { */

#include <readline/readline.h>
#include <readline/history.h>
#define lua_initreadline(L)	((void)L, rl_readline_name="lua")
#define lua_readline(L,b,p)	((void)L, ((b)=readline(p)) != NULL)
#define lua_saveline(L,line)	((void)L, add_history(line))
#define lua_freeline(L,b)	((void)L, free(b))

#elif defined(LUA_USE_LINENOISE) ||    \
      defined(LUA_USE_LINENOISE_UTF8)

#include "linenoise.h"
#if  defined(LUA_USE_LINENOISE_UTF8)
#include "encodings/utf8.h"
#endif
#define lua_initreadline(L)  ((void)L)
#define lua_readline(L,b,p)	((void)L, ((b)=linenoise(p)) != NULL)
#define lua_saveline(L,line)	((void)L, linenoiseHistoryAdd(line))
#define lua_freeline(L,b)	((void)L, linenoiseFree(b))

#else				/* }{ */

#define lua_initreadline(L)  ((void)L)
#define lua_readline(L,b,p) \
        ((void)L, fputs(p, stdout), fflush(stdout),  /* show prompt */ \
        fgets(b, LUA_MAXINPUT, stdin) != NULL)  /* get line */
#define lua_saveline(L,line)	{ (void)L; (void)line; }
#define lua_freeline(L,b)	{ (void)L; (void)b; }

#endif				/* } */

#endif				/* } */


/* ------------------------------------------------------------------------ */

/*
** Environment variables and default values:
**
**   - LUA_HISTORY, envvar pointing to history file
**       (default envvar name: "LUA_HISTORY")
**   - LUA_HISTSIZE, envvar specifying size of in-memory history, in lines
**       (default envvar name: "LUA_HISTSIZE")
**   - LUA_HISTFILESIZE, envvar specifying size of history file, in lines
**       (default envvar name: "LUA_HISTFILESIZE")
**   - LUA_HISTCONTROL, envvar specifying handling of history.
**       (default envvar name: "LUA_HISTCONTROL")
**        This is a colon-separated list of values:
**          - ignorespace:  A line beginning with whitespace is not added to history.
**          - ignoredups:   A line identical to the previous line is not added to history.
**          - ignoreboth:   Equivalent to "ignorespace:ignoredups"
**          - erasedups:    A line added to history erases all previous duplicates.
**        Unknown values are silently ignored.
**   - LUA_HISTORY_DEFAULT, default name of history file,
**       should the envvar LUA_HISTORY be unset.
**       (default file name: "~/.lua_history<MAJOR>.<MINOR>")
**   - LUA_HISTSIZE_DEFAULT, default size of in-memory history, in lines
**       (default history size: 500)
*/
#if !defined(LUA_HISTORY)
#define LUA_HISTORY               "LUA_HISTORY"
#endif
#if !defined(LUA_HISTSIZE)
#define LUA_HISTSIZE              "LUA_HISTSIZE"
#endif
#if !defined(LUA_HISTFILESIZE)
#define LUA_HISTFILESIZE          "LUA_HISTFILESIZE"
#endif
#if !defined(LUA_HISTCONTROL)
#define LUA_HISTCONTROL           "LUA_HISTCONTROL"
#endif
#if !defined(LUA_HISTORY_DEFAULT)
#define LUA_HISTORY_DEFAULT       "~/.lua_history" LUA_VERSION_MAJOR "." LUA_VERSION_MINOR
#endif
#if !defined(LUA_HISTSIZE_DEFAULT)
#define LUA_HISTSIZE_DEFAULT      500
#endif


/* ------------------------------------------------------------------------ */

/*
** Global state for access by readline/linenoise callbacks.
**
** This is necessary because neither framework supports userdata.
*/
#define HISTCONTROL_NONE        0UL
#define HISTCONTROL_IGNORESPACE 1UL <<  0
#define HISTCONTROL_IGNOREDUPS  1UL <<  1
#define HISTCONTROL_IGNOREBOTH  (HISTCONTROL_IGNORESPACE |\
                                 HISTCONTROL_IGNOREDUPS)
#define HISTCONTROL_ERASEDUPS   1UL <<  2

static lua_State*  lua_rl_L = NULL;
static char*       lua_rl_history = NULL;
static long        lua_rl_histsize = 0;
static long        lua_rl_histfilesize = 0;
static long        lua_rl_histcontrol = HISTCONTROL_NONE;


/* ------------------------------------------------------------------------ */

/*
** Return the path that should be used in the place of this filename.
**
** Cases to be handled:
**   - For a NULL filename:
**     - If LUA_HISTORY_DEFAULT is NULL, return NULL
**     - Else substitute filename with LUA_HISTORY_DEFAULT and proceed.
**   - For a filename equal to "", "." or "..", or ending with
**     "/", "/." or "/..", return NULL
**   - For a filename starting with "~/", or with no separator,
**         return $HOME+"/"+filename (with "~/" prefix deleted)
**   - Otherwise, return a copy of filename
**
** The returned path must be free()'d afterwards.
*/
static char* lua_rl_history_compute(const char* name){
  char*  pathbuf;
  size_t pathlen;
  int    need_home;
  const char* segm;
  const char* tail;
  const char* home = "";
  const char* sepr = "";

  if(!name && !(name = LUA_HISTORY_DEFAULT))
    return NULL;

  segm = strrchr(name, '/');
  tail = segm ? segm+1 : name;
  if(strcmp(tail, "")   == 0 ||
     strcmp(tail, ".")  == 0 ||
     strcmp(tail, "..") == 0)
    return NULL;

  if(strncmp(name, "~/", 2) == 0)
    need_home = 1, name += 2;
  else
    need_home = !segm;

  if(need_home){
    sepr = "/";
    home = getenv("HOME");
#if defined(_WIN32)
    if(!home) /* Cargo-culting from GNU readline */
      home = getenv("APPDATA");
#endif
    if(!home)
      return NULL;
  }

  pathlen = snprintf(NULL, 0, "%s%s%s", home, sepr, name);
  pathbuf = (char*)malloc(++pathlen);
  if(!pathbuf)
    return NULL;
  snprintf(pathbuf, pathlen,  "%s%s%s", home, sepr, name);
  return pathbuf;
}


/*
** Return the analyzed history-control flags from their string form.
**
** Cases to be handled:
**   - ignoredups
**   - ignorespace
**   - ignoreboth (ignorespace+ignoredups)
**   - erasedups
*/
static long lua_rl_histcontrol_compute(const char* p){
  const char* q;
  long flags = HISTCONTROL_NONE;
  if(!p)
    return HISTCONTROL_IGNORESPACE;
  do{
    q = strchr(p, ':');
    q = q ? q : p+strlen(p);
    switch(q-p){
      case  9: if(memcmp(p, "erasedups", q-p) == 0)
                 flags |= HISTCONTROL_ERASEDUPS;
               break;
      case 10: if(memcmp(p, "ignoredups", q-p) == 0)
                 flags |= HISTCONTROL_IGNOREDUPS;
               if(memcmp(p, "ignoreboth", q-p) == 0)
                 flags |= HISTCONTROL_IGNOREBOTH;
               break;
      case 11: if(memcmp(p, "ignorespace", q-p) == 0)
                 flags |= HISTCONTROL_IGNORESPACE;
      default: break;
    }
  }while(*q);
  return flags;
}


/*
** Lua 5.4.4 advanced readline support for the GNU readline and history
** libraries or compatible replacements.
**
** Author: Mike Pall.
** Maintainer: Sean Bolton (sean at smbolton dot com).
**
** Copyright (C) 2004-2006, 2014 Mike Pall. Same license as Lua. See lua.h.
**
** Advanced features:
** - Completion of keywords and global variable names.
** - Recursive and metatable-aware completion of variable names.
** - Context sensitive delimiter completion.
** - Save/restore of the history to/from a file (LUA_HISTORY env variable).
** - Setting a limit for the size of the history (LUA_HISTSIZE env variable).
** - Setting the app name to allow for $if lua ... $endif in ~/.inputrc.
**
** Start lua and try these (replace ~ with the TAB key):
**
** ~~
** fu~foo() ret~fa~end<CR>
** io~~~s~~~o~~~w~"foo\n")<CR>
**
** The ~~ are just for demonstration purposes (io~s~o~w~ suffices, of course).
**
** If you are used to zsh/tcsh-style completion support, try adding
** 'TAB: menu-complete' and 'C-d: possible-completions' to your ~/.inputrc.
**
** The patch has been successfully tested with:
**
** GNU    readline 8.1    (2022-06-29)
**
** Change Log:
** 2004-2006  Mike Pall   - original patch
** 2009/08/24 Sean Bolton - updated for GNU readline version 6
** 2011/11/15 Sean Bolton - updated for Lua 5.2
** 2011/12/14 Sean Bolton - fixed segfault when using Mac OS X libedit 2.11
** 2014/08/07 Sean Bolton - updated for Lua 5.3.0-alpha
** 2015/06/17 Sean Bolton - updated for Lua 5.3.1
** 2015/06/17 Olexa Bilaniuk - updated for Lua 5.4.4 + linenoise.
*/

#include <ctype.h>


/* Reserved keywords. */
static const char *const lua_rl_keywords[] = {
  "and", "break", "do", "else", "elseif", "end", "false",
  "for", "function", "goto", "if", "in", "local", "nil", "not", "or",
  "repeat", "return", "then", "true", "until", "while", NULL
};

static int valididentifier(const char *s)
{
  if (!(isalpha(*s) || *s == '_')) return 0;
  while(*++s) if (!(isalpha(*s) || isdigit(*s) || *s == '_')) return 0;
  return 1;
}

/* Get __index field of metatable of object on top of stack. */
static int lua_rl_getmetaindex(lua_State *L)
{
  if (!lua_getmetatable(L, -1)) { lua_pop(L, 1); return 0; }
  lua_pushstring(L, "__index");
  lua_rawget(L, -2);
  lua_replace(L, -2);
  if (lua_isnil(L, -1) || lua_rawequal(L, -1, -2)) { lua_pop(L, 2); return 0; }
  lua_replace(L, -2);
  return 1;
}  /* 1: obj -- val, 0: obj -- */

/* Get field from object on top of stack. Avoid calling metamethods. */
static int lua_rl_getfield(lua_State *L, const char *s, size_t n)
{
  int i = 20;  /* Avoid infinite metatable loops. */
  do {
    if (lua_istable(L, -1)) {
      lua_pushlstring(L, s, n);
      lua_rawget(L, -2);
      if (!lua_isnil(L, -1)) { lua_replace(L, -2); return 1; }
      lua_pop(L, 1);
    }
  } while (--i > 0 && lua_rl_getmetaindex(L));
  lua_pop(L, 1);
  return 0;
}  /* 1: obj -- val, 0: obj -- */


#if defined(LUA_USE_READLINE)

/* Dynamically resizable match list. */
typedef struct {
  char **list;
  size_t idx, allocated, matchlen;
} dmlist;

/* Add prefix + string + suffix to list and compute common prefix. */
static int lua_rl_dmadd(dmlist *ml, const char *p, size_t pn, const char *s,
			int suf)
{
  char *t = NULL;

  if (ml->idx+1 >= ml->allocated &&
      !(ml->list = (char**)realloc(ml->list, sizeof(char *)*(ml->allocated += 32))))
    return -1;

  if (s) {
    size_t n = strlen(s);
    if (!(t = (char *)malloc(sizeof(char)*(pn+n+(suf?2:1))))) return 1;
    memcpy(t, p, pn);
    memcpy(t+pn, s, n);
    n += pn;
    t[n] = suf;
    if (suf) t[++n] = '\0';

    if (ml->idx == 0) {
      ml->matchlen = n;
    } else {
      size_t i;
      for (i = 0; i < ml->matchlen && i < n && ml->list[1][i] == t[i]; i++) ;
      ml->matchlen = i;  /* Set matchlen to common prefix. */
    }
  }

  ml->list[++ml->idx] = t;
  return 0;
}

/* Completion callback. */
static char **lua_rl_complete(const char *text, int start, int end)
{
  lua_State *L = lua_rl_L;
  dmlist ml;
  const char *s;
  size_t i, n, dot, loop;
  int savetop;

  if (!(text[0] == '\0' || isalpha(text[0]) || text[0] == '_')) return NULL;

  ml.list = NULL;
  ml.idx = ml.allocated = ml.matchlen = 0;

  savetop = lua_gettop(L);
  lua_pushglobaltable(L);
  for (n = (size_t)(end-start), i = dot = 0; i < n; i++)
    if (text[i] == '.' || text[i] == ':') {
      if (!lua_rl_getfield(L, text+dot, i-dot))
        goto error;  /* Invalid prefix. */
      dot = i+1;  /* Points to first char after dot/colon. */
    }

  /* Add all matches against keywords if there is no dot/colon. */
  if (dot == 0)
    for (i = 0; (s=lua_rl_keywords[i]); i++)
      if (!strncmp(s, text, n) && lua_rl_dmadd(&ml, NULL, 0, s, ' '))
        goto error;

  /* Add all valid matches from all tables/metatables. */
  loop = 0;  /* Avoid infinite metatable loops. */
  lua_pushglobaltable(L);
  lua_insert(L, -2);
  do {
    if (lua_istable(L, -1) && (loop == 0 || !lua_rawequal(L, -1, -2)))
      for (lua_pushnil(L); lua_next(L, -2); lua_pop(L, 1))
  if (lua_type(L, -2) == LUA_TSTRING) {
    s = lua_tostring(L, -2);
    /* Only match names starting with '_' if explicitly requested. */
    if (!strncmp(s, text+dot, n-dot) && valididentifier(s) &&
        (*s != '_' || text[dot] == '_')) {
      int suf = ' ';  /* Default suffix is a space. */
      switch (lua_type(L, -1)) {
      case LUA_TTABLE:	suf = '.'; break;  /* No way to guess ':'. */
      case LUA_TFUNCTION:	suf = '('; break;
      case LUA_TUSERDATA:
        if (lua_getmetatable(L, -1)) { lua_pop(L, 1); suf = ':'; }
        break;
      }
      if (lua_rl_dmadd(&ml, text, dot, s, suf)) goto error;
    }
  }
  } while (++loop < 20 && lua_rl_getmetaindex(L));
  lua_pop(L, 1);

  if (ml.idx == 0) {
error:
    lua_settop(L, savetop);
    return NULL;
  } else {
    /* list[0] holds the common prefix of all matches (may be ""). */
    /* If there is only one match, list[0] and list[1] will be the same. */
    if (!(ml.list[0] = (char *)malloc(sizeof(char)*(ml.matchlen+1))))
      goto error;
    memcpy(ml.list[0], ml.list[1], ml.matchlen);
    ml.list[0][ml.matchlen] = '\0';
    /* Add the NULL list terminator. */
    if (lua_rl_dmadd(&ml, NULL, 0, NULL, 0)) goto error;
  }

  lua_settop(L, savetop);
#if RL_READLINE_VERSION >= 0x0600
  rl_completion_suppress_append = 1;
#endif
  return ml.list;
}

#elif defined(LUA_USE_LINENOISE) || \
      defined(LUA_USE_LINENOISE_UTF8)

static void lua_rl_dmadd(linenoiseCompletions *lc, const char *fmt, ...) {
    va_list ap;
    size_t len;
    char *copy;

    va_start(ap, fmt);
    len = vsnprintf(NULL, 0, fmt, ap);
    va_end(ap);

    copy = (char*)malloc(len+1);
    if (!copy) return;

    va_start(ap, fmt);
    vsnprintf(copy, len+1, fmt, ap);
    va_end(ap);

    linenoiseAddCompletion(lc, copy);
    free(copy);
}

static void lua_rl_complete(const char *t, linenoiseCompletions *lc){
  lua_State* L = lua_rl_L;
  const char *s;
  size_t i, n, dot, loop;
  int savetop;

  if(!(*t == '\0' || *t == '_' || isalpha(*t))) return;

  /* Drill down from global table. */
  savetop = lua_gettop(L);
  lua_pushglobaltable(L);
  for(n=strlen(t), i=dot=0; i<n; i++)
    if(t[i] == '.' || t[i] == ':'){
      if(!lua_rl_getfield(L, t+dot, i-dot))
        goto error;  /* Invalid prefix. */
      dot = i+1;  /* Points to first char after dot/colon. */
    }

  /* Add all matches against keywords if there is no dot/colon. */
  if(!dot)
    for(i=0; (s=lua_rl_keywords[i]); i++)
      if(strncmp(s, t, n) == 0)
        lua_rl_dmadd(lc, "%s ", s);

  /* Add all valid matches from all tables/metatables. */
  loop = 0;  /* Avoid infinite metatable loops. */
  lua_pushglobaltable(L);
  lua_insert(L, -2);
  do{
    if(lua_istable(L, -1) && (loop == 0 || !lua_rawequal(L, -1, -2)))
      for(lua_pushnil(L); lua_next(L, -2); lua_pop(L, 1))
        if(lua_type(L, -2) == LUA_TSTRING){
          s = lua_tostring(L, -2);
          /* Only match names starting with '_' if explicitly requested. */
          if(!strncmp(s, t+dot, n-dot) && valididentifier(s) &&
             (*s != '_' || t[dot] == '_')){
            int suf = ' ';  /* Default suffix is a space. */
            switch(lua_type(L, -1)){
              case LUA_TTABLE:    suf = '.'; break;  /* No way to guess ':'. */
              case LUA_TFUNCTION: suf = '('; break;
              case LUA_TUSERDATA:
                if(lua_getmetatable(L, -1)){
                  lua_pop(L, 1); suf = ':';
                }
              break;
            }
            lua_rl_dmadd(lc, "%*.*s%s%c", (int)dot, (int)dot, t, s, suf);
          }
        }
  }while(++loop < 20 && lua_rl_getmetaindex(L));
  lua_pop(L, 1);

  error:
  lua_settop(L, savetop);
}

static char* lua_rl_hints(const char *t, int *color, int *bold){
  *color = 0;
  *bold  = 0;
  (void)t;
  return NULL;
}

#endif


/* Initialize readline library. */
static void lua_rl_init(lua_State *L){
  char* p;

  /*
  ** Lua context: Autocomplete callbacks don't accept userdata, must use
  ** global contexts.
  */
  lua_rl_L = L;

  /*
  ** LUA_HISTORY: The path to the command history file.
  ** If NULL, history is not saved.
  ** If not openable for reading, the in-memory history is not initialized.
  ** If not openable for writing, history is not saved on exit.
  **
  ** LUA_HISTCONTROL: Options for history handling.
  **   - LUA_USE_READLINE:  Ignored
  **   - LUA_USE_LINENOISE: Ignored if LUA_USE_LINENOISE_HISTCONTROL not set.
  */
  lua_rl_history     = lua_rl_history_compute    (getenv(LUA_HISTORY));
  lua_rl_histcontrol = lua_rl_histcontrol_compute(getenv(LUA_HISTCONTROL));

  /*
  ** LUA_HISTSIZE: The size of the in-memory command history. If 0, no
  ** commands are saved in the history. If unset, LUA_HISTSIZE_DEFAULT
  ** commands are saved. If negative or non-integer, then:
  **   - LUA_USE_READLINE:  No limit on history.
  **   - LUA_USE_LINENOISE: LUA_HISTSIZE_DEFAULT lines are saved
  **                        (linenoise does not support unlimited history)
  */
  p = getenv(LUA_HISTSIZE);
  if(p){
    lua_rl_histsize = strtol(p, &p, 0);
    if(*p || lua_rl_histsize < 0)
      lua_rl_histsize = -1;
  }else{
    lua_rl_histsize = LUA_HISTSIZE_DEFAULT;
  }

  /*
  ** LUA_HISTFILESIZE: The size of the command history file, LUA_HISTORY.
  ** When set to a non-negative integer, the history file will be truncated to
  ** that size on exit. If set to a negative or non-integer value, history is
  ** not saved to LUA_HISTORY, and it is not truncated. If unset, inherits the
  ** value of LUA_HISTSIZE.
  */
  p = getenv(LUA_HISTFILESIZE);
  if(p){
    lua_rl_histfilesize = strtol(p, &p, 0);
    if(*p || lua_rl_histfilesize < 0)
      lua_rl_histfilesize = -1;
  }else{
    lua_rl_histfilesize = lua_rl_histsize;
  }

#if   defined(LUA_USE_READLINE)
  /* The following is adapted from Mike Pall's & Sean Bolton's Lua patches. */
  /* This allows for $if lua ... $endif in ~/.inputrc. */
  rl_readline_name = "lua";
  /* Break words at every non-identifier character except '.' and ':'. */
  rl_completer_word_break_characters =
    (char*)"\t\r\n !\"#$%&'()*+,-/;<=>?@[\\]^`{|}~";
  rl_completer_quote_characters = "\"'";
#if RL_READLINE_VERSION < 0x0600
  rl_completion_append_character = '\0';
#endif
  rl_attempted_completion_function = lua_rl_complete;
  rl_initialize();

  /* Start using history, optionally set history size and load history file. */
  using_history();
  if(lua_rl_histsize < 0)
    unstifle_history();
  else
    stifle_history(lua_rl_histsize);

  if(lua_rl_history)
    read_history(lua_rl_history);

#elif defined(LUA_USE_LINENOISE) || \
      defined(LUA_USE_LINENOISE_UTF8)

  linenoiseSetMultiLine(1);
  linenoiseHistorySetMaxLen(lua_rl_histsize);
  linenoiseSetCompletionCallback(lua_rl_complete);
  linenoiseSetHintsCallback(lua_rl_hints);
#if defined(LUA_USE_LINENOISE_UTF8)
  linenoiseSetEncodingFunctions(linenoiseUtf8PrevCharLen,
                                linenoiseUtf8NextCharLen,
                                linenoiseUtf8ReadCode);
#endif
#if defined(LUA_USE_LINENOISE_HISTCONTROL)
  linenoiseSetIgnoreSpaces(!!(lua_rl_histcontrol & HISTCONTROL_IGNORESPACE));
  linenoiseSetIgnoreDups  (!!(lua_rl_histcontrol & HISTCONTROL_IGNOREDUPS));
  linenoiseSetEraseDups   (!!(lua_rl_histcontrol & HISTCONTROL_ERASEDUPS));
#endif
  if(lua_rl_history)
    linenoiseHistoryLoad(lua_rl_history);

#endif
}


/* Finalize readline library. */
static void lua_rl_exit(lua_State *L){
  char* tmp;
  (void)L; /* Avoid 'unused parameter' warning. */

#if   defined(LUA_USE_READLINE)

  if(lua_rl_histfilesize >= 0){
    stifle_history(lua_rl_histfilesize);
    if(lua_rl_history)
      write_history(lua_rl_history);
  }

#elif defined(LUA_USE_LINENOISE) || \
      defined(LUA_USE_LINENOISE_UTF8)

  if(lua_rl_histfilesize >= 0){
    linenoiseHistorySetMaxLen(lua_rl_histfilesize);
    if(lua_rl_history)
      linenoiseHistorySave(lua_rl_history);
  }

#endif

  /* free() the lua_rl_history malloc()'ed in lua_rl_init() here */
  tmp = lua_rl_history;
  lua_rl_history = NULL;
  free(tmp);
}

/* ------------------------------------------------------------------------ */



/*
** Return the string to be used as a prompt by the interpreter. Leave
** the string (or nil, if using the default value) on the stack, to keep
** it anchored.
*/
static const char *get_prompt (lua_State *L, int firstline) {
  if (lua_getglobal(L, firstline ? "_PROMPT" : "_PROMPT2") == LUA_TNIL)
    return (firstline ? LUA_PROMPT : LUA_PROMPT2);  /* use the default */
  else {  /* apply 'tostring' over the value */
    const char *p = luaL_tolstring(L, -1, NULL);
    lua_remove(L, -2);  /* remove original value */
    return p;
  }
}

/* mark in error messages for incomplete statements */
#define EOFMARK		"<eof>"
#define marklen		(sizeof(EOFMARK)/sizeof(char) - 1)


/*
** Check whether 'status' signals a syntax error and the error
** message at the top of the stack ends with the above mark for
** incomplete statements.
*/
static int incomplete (lua_State *L, int status) {
  if (status == LUA_ERRSYNTAX) {
    size_t lmsg;
    const char *msg = lua_tolstring(L, -1, &lmsg);
    if (lmsg >= marklen && strcmp(msg + lmsg - marklen, EOFMARK) == 0) {
      lua_pop(L, 1);
      return 1;
    }
  }
  return 0;  /* else... */
}


/*
** Prompt the user, read a line, and push it into the Lua stack.
*/
static int pushline (lua_State *L, int firstline) {
  char buffer[LUA_MAXINPUT];
  char *b = buffer;
  size_t l;
  const char *prmt = get_prompt(L, firstline);
  int readstatus = lua_readline(L, b, prmt);
  if (readstatus == 0)
    return 0;  /* no input (prompt will be popped by caller) */
  lua_pop(L, 1);  /* remove prompt */
  l = strlen(b);
  if (l > 0 && b[l-1] == '\n')  /* line ends with newline? */
    b[--l] = '\0';  /* remove it */
  if (firstline && b[0] == '=')  /* for compatibility with 5.2, ... */
    lua_pushfstring(L, "return %s", b + 1);  /* change '=' to 'return' */
  else
    lua_pushlstring(L, b, l);
  lua_freeline(L, b);
  return 1;
}


/*
** Try to compile line on the stack as 'return <line>;'; on return, stack
** has either compiled chunk or original line (if compilation failed).
*/
static int addreturn (lua_State *L) {
  const char *line = lua_tostring(L, -1);  /* original line */
  const char *retline = lua_pushfstring(L, "return %s;", line);
  int status = luaL_loadbuffer(L, retline, strlen(retline), "=stdin");
  if (status == LUA_OK) {
    lua_remove(L, -2);  /* remove modified line */
    if (line[0] != '\0')  /* non empty? */
      lua_saveline(L, line);  /* keep history */
  }
  else
    lua_pop(L, 2);  /* pop result from 'luaL_loadbuffer' and modified line */
  return status;
}


/*
** Read multiple lines until a complete Lua statement
*/
static int multiline (lua_State *L) {
  for (;;) {  /* repeat until gets a complete statement */
    size_t len;
    const char *line = lua_tolstring(L, 1, &len);  /* get what it has */
    int status = luaL_loadbuffer(L, line, len, "=stdin");  /* try it */
    if (!incomplete(L, status) || !pushline(L, 0)) {
      lua_saveline(L, line);  /* keep history */
      return status;  /* cannot or should not try to add continuation line */
    }
    lua_pushliteral(L, "\n");  /* add newline... */
    lua_insert(L, -2);  /* ...between the two lines */
    lua_concat(L, 3);  /* join them */
  }
}


/*
** Read a line and try to load (compile) it first as an expression (by
** adding "return " in front of it) and second as a statement. Return
** the final status of load/call with the resulting function (if any)
** in the top of the stack.
*/
static int loadline (lua_State *L) {
  int status;
  lua_settop(L, 0);
  if (!pushline(L, 1))
    return -1;  /* no input */
  if ((status = addreturn(L)) != LUA_OK)  /* 'return ...' did not work? */
    status = multiline(L);  /* try as command, maybe with continuation lines */
  lua_remove(L, 1);  /* remove line from the stack */
  lua_assert(lua_gettop(L) == 1);
  return status;
}


/*
** Prints (calling the Lua 'print' function) any values on the stack
*/
static void l_print (lua_State *L) {
  int n = lua_gettop(L);
  if (n > 0) {  /* any result to be printed? */
    luaL_checkstack(L, LUA_MINSTACK, "too many results to print");
    lua_getglobal(L, "print");
    lua_insert(L, 1);
    if (lua_pcall(L, n, 0, 0) != LUA_OK)
      l_message(progname, lua_pushfstring(L, "error calling 'print' (%s)",
                                             lua_tostring(L, -1)));
  }
}


/*
** Do the REPL: repeatedly read (load) a line, evaluate (call) it, and
** print any results.
*/
static void doREPL (lua_State *L) {
  int status;
  const char *oldprogname = progname;
  progname = NULL;  /* no 'progname' on errors in interactive mode */
  lua_rl_init(L);
  while ((status = loadline(L)) != -1) {
    if (status == LUA_OK)
      status = docall(L, 0, LUA_MULTRET);
    if (status == LUA_OK) l_print(L);
    else report(L, status);
  }
  lua_settop(L, 0);  /* clear stack */
  lua_writeline();
  lua_rl_exit(L);
  progname = oldprogname;
}

/* }================================================================== */


/*
** Main body of stand-alone interpreter (to be called in protected mode).
** Reads the options and handles them all.
*/
static int pmain (lua_State *L) {
  int argc = (int)lua_tointeger(L, 1);
  char **argv = (char **)lua_touserdata(L, 2);
  int script;
  int args = collectargs(argv, &script);
  int optlim = (script > 0) ? script : argc; /* first argv not an option */
  luaL_checkversion(L);  /* check that interpreter has correct version */
  if (args == has_error) {  /* bad arg? */
    print_usage(argv[script]);  /* 'script' has index of bad arg. */
    return 0;
  }
  if (args & has_v)  /* option '-v'? */
    print_version();
  if (args & has_E) {  /* option '-E'? */
    lua_pushboolean(L, 1);  /* signal for libraries to ignore env. vars. */
    lua_setfield(L, LUA_REGISTRYINDEX, "LUA_NOENV");
  }
  luaL_openlibs(L);  /* open standard libraries */
  createargtable(L, argv, argc, script);  /* create table 'arg' */
  lua_gc(L, LUA_GCRESTART);  /* start GC... */
  lua_gc(L, LUA_GCGEN, 0, 0);  /* ...in generational mode */
  if (!(args & has_E)) {  /* no option '-E'? */
    if (handle_luainit(L) != LUA_OK)  /* run LUA_INIT */
      return 0;  /* error running LUA_INIT */
  }
  if (!runargs(L, argv, optlim))  /* execute arguments -e and -l */
    return 0;  /* something failed */
  if (script > 0) {  /* execute main script (if there is one) */
    if (handle_script(L, argv + script) != LUA_OK)
      return 0;  /* interrupt in case of error */
  }
  if (args & has_i)  /* -i option? */
    doREPL(L);  /* do read-eval-print loop */
  else if (script < 1 && !(args & (has_e | has_v))) { /* no active option? */
    if (lua_stdin_is_tty()) {  /* running in interactive mode? */
      print_version();
      doREPL(L);  /* do read-eval-print loop */
    }
    else dofile(L, NULL);  /* executes stdin as a file */
  }
  lua_pushboolean(L, 1);  /* signal no errors */
  return 1;
}


#ifndef main_lua
#define main_lua main
#endif
int main_lua (int argc, char **argv) {
  int status, result;
  lua_State *L = luaL_newstate();  /* create state */
  if (L == NULL) {
    l_message(argv[0], "cannot create state: not enough memory");
    return EXIT_FAILURE;
  }
  lua_gc(L, LUA_GCSTOP);  /* stop GC while building state */
  lua_pushcfunction(L, &pmain);  /* to call 'pmain' in protected mode */
  lua_pushinteger(L, argc);  /* 1st argument */
  lua_pushlightuserdata(L, argv); /* 2nd argument */
  status = lua_pcall(L, 2, 1, 0);  /* do the call */
  result = lua_toboolean(L, -1);  /* get result */
  report(L, status);
  lua_close(L);
  return (result && status == LUA_OK) ? EXIT_SUCCESS : EXIT_FAILURE;
}

